name: CI Pipeline

on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e backend/.[test]
      - run: pytest backend/tests/
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }} # TODO: pls DON'T FORGET - Add secret to github repo!!!!!

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci --prefix frontend
      - run: npm test --prefix frontend
